### PR TITLE
Initialize .npmignore

### PR DESCRIPTION
**Pull request by manosim**
When publishing to npm, instead of using the `.gitignore`, the file `.npmignore` will be used so that specific directories (like `/dist`) will be included in the release but won’t be committed to GitHub.

Same applies for files like `.babelrc` & `.travis.yml` (these are included in git but ignored when publishing to npm)

The tests will be fixed once #7 gets merged.

Ps. Also cleans up the `.gitignore` file.

### CODE REVIEW

**Comment by tomchristie** [comment]
Build restarted.

**Comment by manosim** [comment]
@tomchristie I've also added a script called `prepublish` so that every time we run `npm publish`, it will first create the bundle `dist/coreapi.js`.

**Comment by tomchristie** [comment]
Not obvious why the test results changed, only after adding `prepublish`  - seems completely unreleated.

**Comment by manosim** [comment]
It looks like running `npm install` also runs `npm run prepublish`. I've made travis run `npm install` but not `npm run prepublish`.

Also the `dist/` is now included in source but all files inside will be ignored. Currently if you clone the project, browserify fails to create the bundle because `dist/` does not exist.

**Comment by tomchristie** [comment]
👍

**Pull request merged**
